import { SimulationRequest, SimulationResponse } from '@/types/negotiation';

export const exportService = {
  // Export as JSON
  exportJSON: (request: SimulationRequest, response: SimulationResponse, filename?: string) => {
    const data = {
      request,
      response,
      exportedAt: new Date().toISOString(),
    };

    const json = JSON.stringify(data, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename || `negotiation_${Date.now()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  // Export as Text
  exportText: (request: SimulationRequest, response: SimulationResponse, filename?: string) => {
    const text = `
SUSTAINABLE NEGOTIATION AI - RESULTS
=====================================

Generated: ${new Date().toLocaleString()}

PARTIES
-------
Party A: ${request.partyA.name}
Goals: ${request.partyA.goals}
Constraints: ${request.partyA.constraints}

Party B: ${request.partyB.name}
Goals: ${request.partyB.goals}
Constraints: ${request.partyB.constraints}

ESG PRIORITIES
--------------
Environmental: ${request.esg.environmental}/100
Social: ${request.esg.social}/100
Governance: ${request.esg.governance}/100

IMPACT SCORES
-------------
Economic: ${response.scores.economic}/100
Social: ${response.scores.social}/100
Environmental: ${response.scores.environmental}/100

AI-GENERATED COMPROMISES
========================

ECONOMIC-OPTIMIZED COMPROMISE
------------------------------
${response.economic_compromise}

SOCIAL-OPTIMIZED COMPROMISE
---------------------------
${response.social_compromise}

BALANCED SUSTAINABLE COMPROMISE
-------------------------------
${response.balanced_compromise}

---
Generated by Sustainable Negotiation AI
`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename || `negotiation_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  // Copy to clipboard
  copyToClipboard: async (request: SimulationRequest, response: SimulationResponse): Promise<boolean> => {
    const text = `Negotiation: ${request.partyA.name} vs ${request.partyB.name}

Economic Score: ${response.scores.economic}
Social Score: ${response.scores.social}
Environmental Score: ${response.scores.environmental}

Economic Compromise:
${response.economic_compromise}

Social Compromise:
${response.social_compromise}

Balanced Compromise:
${response.balanced_compromise}`;

    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (err) {
      console.error('Failed to copy:', err);
      return false;
    }
  },

  // Generate shareable link (simplified version - stores in URL params)
  generateShareLink: (request: SimulationRequest, response: SimulationResponse): string => {
    const data = {
      partyA: request.partyA.name,
      partyB: request.partyB.name,
      scores: response.scores,
    };
    const encoded = btoa(JSON.stringify(data));
    return `${window.location.origin}/share?data=${encoded}`;
  },
};
